version: '3'
services:
  centos7:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.centos-7
      args:
        GO_VERSION: 1.11
    volumes:
      - $GOPATH:/go
    environment:
      DIST: el7
    command: make rpm
  centos6:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.centos-6
      args:
        GO_VERSION: 1.11
    volumes:
      - $GOPATH:/go
    environment:
      DIST: el6
    command: make rpm
  debian8:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debian-8
      args:
        GO_VERSION: 1.11
    volumes:
      - $GOPATH:/go
    environment:
      DIST: jessie
    command: make deb_systemd
  debian9:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debian-9
      args:
        GO_VERSION: 1.11
    volumes:
      - $GOPATH:/go
    environment:
      DIST: stretch
    command: make deb_systemd
  ubuntu14:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-14
      args:
        GO_VERSION: 1.11
    volumes:
      - $GOPATH:/go
    environment:
      DIST: trusty
    command: make deb_sysv
  ubuntu16:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-16
      args:
        GO_VERSION: 1.11
    volumes:
      - $GOPATH:/go
    environment:
      DIST: xenial
    command: make deb_systemd
  ubuntu18:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-18
      args:
        GO_VERSION: 1.11
    volumes:
      - $GOPATH:/go
    environment:
      DIST: bionic
    command: make deb_systemd
