version: '3'
services:
  centos8:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.centos-8
      args:
        GO_VERSION: 1.17.2
    volumes:
      - .:/go/src/github.com/STNS/STNS
      - ~/pkg:/go/pkg
    environment:
      DIST: el8
    command: make rpm
  centos7:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.centos-7
      args:
        GO_VERSION: 1.17.2
    volumes:
      - .:/go/src/github.com/STNS/STNS
      - ~/pkg:/go/pkg
    environment:
      DIST: el7
    command: make rpm
  ubuntu16:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-16
      args:
        GO_VERSION: 1.17.2
    volumes:
      - .:/go/src/github.com/STNS/STNS
      - ~/pkg:/go/pkg
    environment:
      DIST: xenial
    command: make deb
  ubuntu18:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-18
      args:
        GO_VERSION: 1.17.2
    volumes:
      - .:/go/src/github.com/STNS/STNS
      - ~/pkg:/go/pkg
    environment:
      DIST: bionic
    command: make deb
  ubuntu20:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-20
      args:
        GO_VERSION: 1.17.2
    volumes:
      - .:/go/src/github.com/STNS/STNS
      - ~/pkg:/go/pkg
    environment:
      DIST: focal
    command: make deb
  debian8:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debian-8
      args:
        GO_VERSION: 1.17.2
    volumes:
      - .:/go/src/github.com/STNS/STNS
      - ~/pkg:/go/pkg
    environment:
      DIST: jessie
    command: make deb
  debian9:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debian-9
      args:
        GO_VERSION: 1.17.2
    volumes:
      - .:/go/src/github.com/STNS/STNS
      - ~/pkg:/go/pkg
    environment:
      DIST: stretch
    command: make deb
  debian10:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debian-10
      args:
        GO_VERSION: 1.17.2
    volumes:
      - .:/go/src/github.com/STNS/STNS
      - ~/pkg:/go/pkg
    environment:
      DIST: buster
    command: make deb
  debian11:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debian-11
      args:
        GO_VERSION: 1.17.2
    volumes:
      - .:/go/src/github.com/STNS/STNS
      - ~/pkg:/go/pkg
    environment:
      DIST: bullseye
    command: make deb

