version: '3'
services:
  almalinux9:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.almalinux-9
    volumes:
      - .:/go/src/github.com/STNS/STNS
      - ~/pkg:/go/pkg
    environment:
      DIST: el9
    command: make rpm
  centos7:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.centos-7
    volumes:
      - .:/go/src/github.com/STNS/STNS
      - ~/pkg:/go/pkg
    environment:
      DIST: el7
    command: make rpm
  ubuntu20:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-20
    volumes:
      - .:/go/src/github.com/STNS/STNS
      - ~/pkg:/go/pkg
    environment:
      DIST: focal
    command: make deb
  ubuntu22:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-22
    volumes:
      - .:/go/src/github.com/STNS/STNS
      - ~/pkg:/go/pkg
    environment:
      DIST: jammy
    command: make deb
  debian10:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debian-10
    volumes:
      - .:/go/src/github.com/STNS/STNS
      - ~/pkg:/go/pkg
    environment:
      DIST: buster
    command: make deb
  debian11:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debian-11
    volumes:
      - .:/go/src/github.com/STNS/STNS
      - ~/pkg:/go/pkg
    environment:
      DIST: bullseye
    command: make deb
