version: '3'
services:
  centos7:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.centos-7
      args:
        GO_VERSION: 1.12.1
    volumes:
      - .:/go/src/github.com/STNS/STNS
      - ~/pkg:/go/pkg
    environment:
      DIST: el7
    command: make rpm
  centos6:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.centos-6
      args:
        GO_VERSION: 1.12.1
    volumes:
      - .:/go/src/github.com/STNS/STNS
      - ~/pkg:/go/pkg
    environment:
      DIST: el6
    command: make rpm
  ubuntu16:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-16
      args:
        GO_VERSION: 1.12.1
    volumes:
      - .:/go/src/github.com/STNS/STNS
      - ~/pkg:/go/pkg
    environment:
      DIST: xenial
    command: make deb
