FROM ubuntu:bionic
MAINTAINER pyama86 <www.kazu.com@gmail.com>

RUN apt-get -qq update && \
    apt-get install -qq glibc-source gcc make libcurl4-gnutls-dev libjansson-dev \
                        bzip2 unzip debhelper dh-make devscripts cdbs clang

ENV USER root

RUN mkdir /stns
WORKDIR /stns
