FROM ubuntu:xenial
MAINTAINER pyama86 <www.kazu.com@gmail.com>

RUN apt-get -qqy update && \
    apt-get install -qqy glibc-source gcc make libcurl4-gnutls-dev \
                        bzip2 unzip debhelper dh-make devscripts cdbs clang

ENV USER root

RUN mkdir /stns
WORKDIR /stns
