version: '3'
services:
  nss_centos7:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.centos-7
    volumes:
      - .:/stns
    environment:
      DIST: el7
    command: make rpm
  nss_centos6:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.centos-6
    volumes:
      - .:/stns
    environment:
      DIST: el6
    command: make rpm
  nss_ubuntu16:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-16
    volumes:
      - .:/stns
    environment:
      DIST: xenial
    command: make deb
