FROM centos:7
MAINTAINER pyama86 <www.kazu.com@gmail.com>

RUN yum install -y epel-release rpmdevtools make git
COPY . /go/src/github.com/STNS/STNS
WORKDIR /go/src/github.com/STNS/STNS
RUN git config --global --add safe.directory `pwd`
RUN mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
RUN sed -i "s;%_build_name_fmt.*;%_build_name_fmt\t%%{ARCH}/%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.el7.rpm;" /usr/lib/rpm/macros
