FROM ubuntu:focal
MAINTAINER pyama86 <www.kazu.com@gmail.com>

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -qqy update && \
    apt-get install -qqy gcc make debhelper dh-make devscripts git
ENV USER root
COPY . /go/src/github.com/STNS/STNS
WORKDIR /go/src/github.com/STNS/STNS
RUN git config --global --add safe.directory `pwd`
