FROM debian:buster
MAINTAINER pyama86 <www.kazu.com@gmail.com>
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -qq update && \
    apt-get install -qq gcc make debhelper dh-make devscripts git

RUN ln -s /usr/local/go/bin/go /bin/go
ENV USER root
COPY . /go/src/github.com/STNS/STNS
WORKDIR /go/src/github.com/STNS/STNS
