include = "include.toml"
module_path = "/Users/pyama/Nextcloud/src/github.com/STNS/STNS/tmp/bin"
load_module = "mod_stns_dynamodb.so"
[users.test]
id = 10001
group_id = 10001
password = "$6$baslHey25/SqFuZc$L.DAhnPB9AWZbwa.C12UL81oAQX2G7eUiBUAVuW9ljrsEegoqiinCrpdDqmjJGxZogbdNJ2PWmXtUkmZvsItM0"
keys = ["key1", "key2"]

[users.foo]
id = 10002
group_id = 10002
password = "test"

[groups.test]
id = 10001
users = ["test"]

[groups.bar]
id = 10002
users = ["foo"]

[modules.dynamodb]
sync = false
