name: Release Docker Image
on:
  push:
    branches:
      - default
jobs:
  release:
    runs-on: ubuntu-latest
    if: "contains(github.ref, 'default')"
    steps:
    - uses: actions/checkout@v2
    - run: make build_image
    - name: Run Vulnerability/Security Scanner
      id: run-scanner
      uses: Azure/container-scan@v0
      with:
        image-name: "stns/stns:latest"
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: make push_image
